DROP TABLE IF EXISTS client;

CREATE TABLE client
(
    id   INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS account;

CREATE TABLE account
(
    id        int generated by default as identity (start with 1) primary key,
    number    BIGINT   NOT NULL,
    amount DECIMAL(11, 2) NOT NULL,
    client_id INT            NOT NULL
);

DROP TABLE IF EXISTS card;

CREATE TABLE card
(
    id           int generated by default as identity (start with 1) primary key,
    number       bigint(16)  NOT NULL,
    expDate      varchar(10) NOT NULL,
    cvv       int(3)      NOT NULL,
    account_id int(11)     NOT NULL
);